### ISSUE TITLE
confusing between development_jumpscale and development_builders branches 

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtech/jumpscaleX#745]
There are things works on development_builder but don't work on development_jumpscale  and vice versa 
As Example :
### in development_builders :
j.builders.web.caddy.build() : works
j.builders.web.caddy.start() : fails due this issue https://github.com/threefoldtech/jumpscaleX/issues/728
and this issue solved on development_jumpscale not in development_builders

### in development_jumpscale:
j.builders.web.caddy.build() : fail and all other builders with the following error:
```
JSX> j.builders.web.caddy.build(reset=True)                                                          
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sandbox/lib/jumpscale/Jumpscale/builders/builder/web/BuilderWebFactory.py", line 44, in caddy
    from .BuilderCaddy import BuilderCaddy
  File "/sandbox/lib/jumpscale/Jumpscale/builders/builder/web/BuilderCaddy.py", line 2, in <module>
    from Jumpscale.builder.runtimes.BuilderGolang import BuilderGolangTools
ModuleNotFoundError: No module named 'Jumpscale.builder'

```

**Comment by rkhamis** [comment]
@Dinaamagdy fixed. Please try again, and please use development_jumpscale as it has the latest fixes

**Comment by Dinaamagdy** [comment]
worked on development_jumpscale
## Steps
- j.builders.db.redis.build(), j.builders.db.redis.install(), j.builder.db.redis.start()
- j.builders.web.caddy.build(), j.builders.web.caddy.install(),j.builders.web.caddy.start()

and both works well
