### ISSUE TITLE
jumpscale installation

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/jumpscaleX#747]
Behavior **ON HOST** should be:
 - if no sshagent --> load it with the correct socket
    - if key ---> load
    - if no key -->  ask

In the config file, which key to use is specified

note: loading of key in ssh-agent and starting ssh-agent needs to be automatic

Behavior **ON CONTAINER**:
not in container because then SSH -a which means the ssh-key was forwarded

**Comment by waleedhammam** [comment]
Working on automatic loading ssh-agent with key if available

**Comment by waleedhammam** [comment]
**Change-log**: **Commit**: https://github.com/threefoldtech/jumpscaleX/commit/93a7614c3b1646985de64a736d6e3052ff4d234a, **Branch**: development_jumpscale
- Fix ssh-agent autostart

**Comment by waleedhammam** [comment]
**Change-log**: **Commit**: https://github.com/threefoldtech/jumpscaleX/commit/1fe363b21f54cc05a51935eaf336fd15145279cf, **Branch**: development_jumpscale
- Add default key to silent installation 'id_rsa'.
also can be changed from  `~/sandbox/cfg/jumpscale_config.toml` or `/sandbox/cfg/jumpscale_config.toml` according to your installation type
- Update installation docs @ https://github.com/threefoldtech/jumpscaleX/blob/development_jumpscale/docs/Installation/README.md

**Comment by waleedhammam** [comment]
**Full installation scenario**

**ssh-agent**
1- No ssh-agent loaded
&nbsp;&nbsp;&nbsp;&nbsp; Will load ssh-agent with jsx socket path in {DIR_VAR}/sshagent_socket
2- There's an ssh-agent loaded but invalid socket
&nbsp;&nbsp;&nbsp;&nbsp;Will kill the agent and load new one with the new sockets

**ssh-keys**
1- No sshkey found in ~/.ssh
&nbsp;&nbsp;&nbsp;&nbsp;This will exit the installer with an error message to have a ssh-key
2- Only 1 ssh-key found
&nbsp;&nbsp;&nbsp;&nbsp;Will load this key and continue installation normally
3- More than ssh-key found
&nbsp;&nbsp;&nbsp;&nbsp; will ask you which one to choose

**Comment by waleedhammam** [comment]
- Also added option to clone via http if ssh cloning failed at: https://github.com/threefoldtech/jumpscaleX/commit/336ed259d50da1e3e1a6f0363b9f5eebfc022715 <br/>**branch**: development_jumpscale

**Comment by Pishoy** [comment]
verified all cases in `Full installation scenario`
below are the main steps are repeated on each cases
```
apt install -y openssh-server locales curl vim git rsync unzip lsb python3 python3-pip
 pip3 install click
curl https://raw.githubusercontent.com/threefoldtech/jumpscaleX/development_jumpscale/install/jsx.py?$RANDOM > /tmp/jsx;
 chmod +x /tmp/jsx;
 /tmp/jsx install 
```
 - jsx version 
```
3BOTDEVEL:test:jumpscaleX: git log -1
commit f84f2be4d975e6643e2d7f83c9c2f864042562ec (grafted, HEAD -> development_jumpscale, origin/development_jumpscale)
Author: BolaNasr <bola.nasr@live.com>
Date:   Sun Jul 28 14:46:03 2019 +0200

    add odoo conf
```
