### ISSUE TITLE
error in import data in BCDB

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/jumpscaleX#765]
I got an error while trying to import data in BCDB. 

![ff](https://user-images.githubusercontent.com/21218053/62623664-b8fa9500-b921-11e9-9406-140a8e7f7c14.png)

**Comment by BolaNasr** [comment]
can please pull 
and write ```jsx bcdb-delete```
then try again  in the ```development_jumpscale_logging_errors``` branch

**Comment by Dina-Abd-Elrahman** [comment]
- this issue is solved now after pull the latest changes, but i got this error once i login from kosmos and try to login again 

![ff](https://user-images.githubusercontent.com/21218053/62632716-3b3f8500-b933-11e9-87db-203e6c89aa24.png)

**Comment by Dina-Abd-Elrahman** [comment]
- also i got the same error while trying to remove the database using this command 
`jsx bcdb-delete`

**Comment by Dina-Abd-Elrahman** [comment]
#### Branch: `development_jumpscale_logging_errors`
##### Commit_ID: 4f215a52ce9dcc6826befb2d516ea6a8045cf67c

**Comment by zgorizzo69** [comment]
I am closing this because it is working on development_jumpscale
![bcdb export ok](https://user-images.githubusercontent.com/16853695/63008840-adf4b700-be83-11e9-909f-1ae47fc96cce.png)
