### ISSUE TITLE
js_init generate needs to work multilevel

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX#776]
now only j.something.class...

needs to be able any level as specified in __jslocation__

this will allow us to not have to do manual build of the tree like in builders

**Comment by waleedhammam** [comment]
Still investigating the optimal way to generate all without a factory

**Comment by waleedhammam** [comment]
branch: development_jumpscale_generators
commit: https://github.com/threefoldtech/jumpscaleX/commit/7b45d88981c62f1b7c36698eee66fe7bfbb2fb39

changes:
- allow multi-level generation via jslocation variable in classes
- no need to manual add of builders in factories

bugs:
-  generated classes also appears in the parent group

usage:
- just add __jslocation__ to your builder, server .. etc
ex: `j.builders.runtimes.parent.child`
- Then js_init generate
