### ISSUE TITLE
bug in sonic somewhere

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX#795]
![image](https://user-images.githubusercontent.com/6021844/63346740-f3b6f100-c355-11e9-9d18-0b401e193e3b.png)

**Comment by despiegk** [comment]
![image](https://user-images.githubusercontent.com/6021844/63347205-f239f880-c356-11e9-8d49-757f8b73557b.png)

j.tools.markdowndocs.load_wikis()

**Comment by xmonader** [comment]
sure you have the latest sonic? `pip install -U sonic-client`

**Comment by serboctor** [comment]
Not reproducible.
